// Code generated by cli-generator. DO NOT EDIT.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"time"

	"github.com/spf13/cobra"
)

// Client holds the server URL and auth token for all generated commands.
type Client struct {
	BaseURL    string
	Token      string
	HTTPClient *http.Client
}

// NewClient creates a Client with a default 30s timeout.
func NewClient(baseURL, token string) *Client {
	return &Client{
		BaseURL:    baseURL,
		Token:      token,
		HTTPClient: &http.Client{Timeout: 30 * time.Second},
	}
}

// Do performs the HTTP request and pretty-prints the JSON response to stdout.
func (c *Client) Do(method, path string, body map[string]interface{}) error {
	var reqBody io.Reader
	if method != "GET" {
		b, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("failed to marshal request body: %w", err)
		}
		reqBody = bytes.NewReader(b)
	}

	req, err := http.NewRequest(method, c.BaseURL+path, reqBody)
	if err != nil {
		return fmt.Errorf("failed to build request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	if c.Token != "" {
		req.Header.Set("Authorization", "Bearer "+c.Token)
	}

	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read response: %w", err)
	}

	var pretty interface{}
	if json.Unmarshal(respBytes, &pretty) == nil {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		_ = enc.Encode(pretty)
	} else {
		fmt.Fprintln(os.Stdout, string(respBytes))
	}

	if resp.StatusCode >= 400 {
		return fmt.Errorf("server returned %s", resp.Status)
	}
	return nil
}

// RegisterGeneratedCommands registers all auto-generated CLI commands from the OpenAPI spec.
func RegisterGeneratedCommands(root *cobra.Command, client *Client) {
	root.AddCommand(registerCreateRdnsRecordCmd(client))
	root.AddCommand(registerDeleteRdnsRecordCmd(client))
	root.AddCommand(registerListRdnsRecordsCmd(client))
	root.AddCommand(registerUserChangePasswordCmd(client))
	root.AddCommand(registerChangePasswordCmd(client))
	root.AddCommand(registerCreateBackupCmd(client))
	root.AddCommand(registerCreateBackupScheduleCmd(client))
	root.AddCommand(registerCreateFirewallRuleCmd(client))
	root.AddCommand(registerCreateNotificationCmd(client))
	root.AddCommand(registerCreateOrderCmd(client))
	root.AddCommand(registerCreatePowerTaskCmd(client))
	root.AddCommand(registerCreateSnapshotCmd(client))
	root.AddCommand(registerDeleteBackupCmd(client))
	root.AddCommand(registerDeleteBackupScheduleCmd(client))
	root.AddCommand(registerDeleteFirewallRuleCmd(client))
	root.AddCommand(registerDeleteNotificationCmd(client))
	root.AddCommand(registerDeletePowerTaskCmd(client))
	root.AddCommand(registerDeleteSnapshotCmd(client))
	root.AddCommand(registerEditBackupScheduleCmd(client))
	root.AddCommand(registerGetCatalogueCmd(client))
	root.AddCommand(registerGetVpsConfigCmd(client))
	root.AddCommand(registerGetVpsDetailsCmd(client))
	root.AddCommand(registerGetOsTemplateDetailsCmd(client))
	root.AddCommand(registerGetPrivateSshKeyCmd(client))
	root.AddCommand(registerGetPublicSshKeyCmd(client))
	root.AddCommand(registerListAllowedFeaturesCmd(client))
	root.AddCommand(registerListBackupSchedulesCmd(client))
	root.AddCommand(registerListBackupsCmd(client))
	root.AddCommand(registerListFirewallRulesCmd(client))
	root.AddCommand(registerListIsosCmd(client))
	root.AddCommand(registerListNotificationsCmd(client))
	root.AddCommand(registerListOrdersCmd(client))
	root.AddCommand(registerListOsTemplatesCmd(client))
	root.AddCommand(registerListPowerTasksCmd(client))
	root.AddCommand(registerListReinstallOsCmd(client))
	root.AddCommand(registerListSnapshotsCmd(client))
	root.AddCommand(registerListVpsServicesCmd(client))
	root.AddCommand(registerMountIsoCmd(client))
	root.AddCommand(registerMoveFirewallRuleCmd(client))
	root.AddCommand(registerGetNoVncConsoleCmd(client))
	root.AddCommand(registerRebootVpsCmd(client))
	root.AddCommand(registerRestoreBackupCmd(client))
	root.AddCommand(registerRetryPaymentCmd(client))
	root.AddCommand(registerRollbackSnapshotCmd(client))
	root.AddCommand(registerShutdownVpsCmd(client))
	root.AddCommand(registerStartVpsCmd(client))
	root.AddCommand(registerStopVpsCmd(client))
	root.AddCommand(registerSuspendVpsCmd(client))
	root.AddCommand(registerTerminateVpsCmd(client))
	root.AddCommand(registerTriggerReinstallCmd(client))
	root.AddCommand(registerUnsuspendVpsCmd(client))
	root.AddCommand(registerUpdateVpsConfigCmd(client))
	root.AddCommand(registerUpdateFirewallRuleCmd(client))
	root.AddCommand(registerUpdateNotificationCmd(client))
	root.AddCommand(registerUpdatePowerTaskCmd(client))
	root.AddCommand(registerUpdateSnapshotCmd(client))
	root.AddCommand(registerUpdateSshKeysCmd(client))
	root.AddCommand(registerValidatePricingCmd(client))
}

// registerCreateRdnsRecordCmd returns the cobra command for CreateRdnsRecord
// POST /dns/create-rdns-record
func registerCreateRdnsRecordCmd(client *Client) *cobra.Command {
	var flaghostname string
	var flagip string
	var flagrelid int
	var flagttl int
	var flagtype int
	cmd := &cobra.Command{
		Use:   "create-rdns-record",
		Short: "Creates (or upserts) a PTR record for the authenticated client. If the client already owns a PTR for the same (serverid, ip) it is updated in place; if another client owns it a 409 is returned.",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"hostname": flaghostname,
				"ip": flagip,
				"relid": flagrelid,
				"ttl": flagttl,
				"type": flagtype,
			}
			return client.Do("POST", "/dns/create-rdns-record", body)
		},
	}
	cmd.Flags().StringVar(&flaghostname, "hostname", "", "PTR target hostname")
	_ = cmd.MarkFlagRequired("hostname")
	cmd.Flags().StringVar(&flagip, "ip", "", "IPv4 or IPv6 address the PTR record should point from")
	_ = cmd.MarkFlagRequired("ip")
	cmd.Flags().IntVar(&flagrelid, "relid", 0, "Related service id matching the zone type (tblhosting.id, tblhostingaddons.id or tbldomains.id)")
	_ = cmd.MarkFlagRequired("relid")
	cmd.Flags().IntVar(&flagttl, "ttl", 0, "Time-to-live in seconds. Defaults to 14400; clamped to [30, 86400]")
	cmd.Flags().IntVar(&flagtype, "type", 0, "Zone type: 0=OTHER, 1=DOMAIN, 2=HOSTING, 3=ADDON")
	_ = cmd.MarkFlagRequired("type")
	return cmd
}

// registerDeleteRdnsRecordCmd returns the cobra command for DeleteRdnsRecord
// POST /dns/delete-rdns-record
func registerDeleteRdnsRecordCmd(client *Client) *cobra.Command {
	var flagrecord_id int
	cmd := &cobra.Command{
		Use:   "delete-rdns-record",
		Short: "Deletes a PTR (rDNS) record owned by the authenticated client",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"record_id": flagrecord_id,
			}
			return client.Do("POST", "/dns/delete-rdns-record", body)
		},
	}
	cmd.Flags().IntVar(&flagrecord_id, "record_id", 0, "ID of the PTR record to delete")
	_ = cmd.MarkFlagRequired("record_id")
	return cmd
}

// registerListRdnsRecordsCmd returns the cobra command for ListRdnsRecords
// POST /dns/list-rdns-records
func registerListRdnsRecordsCmd(client *Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list-rdns-records",
		Short: "Lists all rDNS (PTR) records and available services for the authenticated client",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
			}
			return client.Do("POST", "/dns/list-rdns-records", body)
		},
	}
	return cmd
}

// registerUserChangePasswordCmd returns the cobra command for UserChangePassword
// POST /user/change-password
func registerUserChangePasswordCmd(client *Client) *cobra.Command {
	var flagconfirm_password string
	var flagold_password string
	var flagpassword string
	cmd := &cobra.Command{
		Use:   "user-change-password",
		Short: "Changes the authenticated user's password. All active sessions will be revoked and the user must login again.",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"confirm_password": flagconfirm_password,
				"old_password": flagold_password,
				"password": flagpassword,
			}
			return client.Do("POST", "/user/change-password", body)
		},
	}
	cmd.Flags().StringVar(&flagconfirm_password, "confirm_password", "", "Confirm new password (must match password)")
	_ = cmd.MarkFlagRequired("confirm_password")
	cmd.Flags().StringVar(&flagold_password, "old_password", "", "Current password")
	_ = cmd.MarkFlagRequired("old_password")
	cmd.Flags().StringVar(&flagpassword, "password", "", "New password")
	_ = cmd.MarkFlagRequired("password")
	return cmd
}

// registerChangePasswordCmd returns the cobra command for ChangePassword
// POST /vps/change-password
func registerChangePasswordCmd(client *Client) *cobra.Command {
	var flagpassword string
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "change-password",
		Short: "Change the root password for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"password": flagpassword,
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/change-password", body)
		},
	}
	cmd.Flags().StringVar(&flagpassword, "password", "", "New root password for the VPS")
	_ = cmd.MarkFlagRequired("password")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerCreateBackupCmd returns the cobra command for CreateBackup
// POST /vps/create-backup
func registerCreateBackupCmd(client *Client) *cobra.Command {
	var flagcompress string
	var flagmode string
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "create-backup",
		Short: "Creates a new backup for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"compress": flagcompress,
				"mode": flagmode,
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/create-backup", body)
		},
	}
	cmd.Flags().StringVar(&flagcompress, "compress", "", "Backup compression type enum")
	cmd.Flags().StringVar(&flagmode, "mode", "", "Backup mode (e.g., snapshot, suspend, stop)")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerCreateBackupScheduleCmd returns the cobra command for CreateBackupSchedule
// POST /vps/create-backup-schedule
func registerCreateBackupScheduleCmd(client *Client) *cobra.Command {
	var flagcompress string
	var flagdow string
	var flagmailto bool
	var flagmode string
	var flagservice_id string
	var flagstarttime string
	cmd := &cobra.Command{
		Use:   "create-backup-schedule",
		Short: "Creates a new backup schedule for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"compress": flagcompress,
				"dow": flagdow,
				"mailto": flagmailto,
				"mode": flagmode,
				"service_id": flagservice_id,
				"starttime": flagstarttime,
			}
			return client.Do("POST", "/vps/create-backup-schedule", body)
		},
	}
	cmd.Flags().StringVar(&flagcompress, "compress", "", "Backup compression type enum")
	_ = cmd.MarkFlagRequired("compress")
	cmd.Flags().StringVar(&flagdow, "dow", "", "Days of week when backup should run. Valid values: mon, tue, wed, thu, fri, sat, sun. Provide as an array of day names.")
	_ = cmd.MarkFlagRequired("dow")
	cmd.Flags().BoolVar(&flagmailto, "mailto", false, "Email notification setting. Set to true to send notifications to client's email, false or omit to disable")
	cmd.Flags().StringVar(&flagmode, "mode", "", "Backup mode. Valid values: 'snapshot', 'suspend', 'stop'")
	_ = cmd.MarkFlagRequired("mode")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	cmd.Flags().StringVar(&flagstarttime, "starttime", "", "Time in HH:MM format (e.g., '03:00'). Hours must be between 00-23, minutes must be between 00-59")
	_ = cmd.MarkFlagRequired("starttime")
	return cmd
}

// registerCreateFirewallRuleCmd returns the cobra command for CreateFirewallRule
// POST /vps/create-firewall-rule
func registerCreateFirewallRuleCmd(client *Client) *cobra.Command {
	var flagcomment string
	var flagdest string
	var flagdport string
	var flagenable int
	var flagiface string
	var flaglog string
	var flagmacro string
	var flagpos int
	var flagproto string
	var flagrule_action string
	var flagservice_id string
	var flagsource string
	var flagsport string
	var flagtype string
	cmd := &cobra.Command{
		Use:   "create-firewall-rule",
		Short: "Creates a new firewall rule for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"comment": flagcomment,
				"dest": flagdest,
				"dport": flagdport,
				"enable": flagenable,
				"iface": flagiface,
				"log": flaglog,
				"macro": flagmacro,
				"pos": flagpos,
				"proto": flagproto,
				"rule_action": flagrule_action,
				"service_id": flagservice_id,
				"source": flagsource,
				"sport": flagsport,
				"type": flagtype,
			}
			return client.Do("POST", "/vps/create-firewall-rule", body)
		},
	}
	cmd.Flags().StringVar(&flagcomment, "comment", "", "Comment/description for the rule")
	cmd.Flags().StringVar(&flagdest, "dest", "", "Destination address/network")
	cmd.Flags().StringVar(&flagdport, "dport", "", "Destination port")
	cmd.Flags().IntVar(&flagenable, "enable", 0, "Whether the rule is enabled (1=enabled, 0=disabled)")
	cmd.Flags().StringVar(&flagiface, "iface", "", "Network interface name")
	cmd.Flags().StringVar(&flaglog, "log", "", "Log level")
	cmd.Flags().StringVar(&flagmacro, "macro", "", "Firewall macro name")
	cmd.Flags().IntVar(&flagpos, "pos", 0, "Position/priority of the rule")
	cmd.Flags().StringVar(&flagproto, "proto", "", "Protocol (tcp, udp, icmp, etc). Use '0' or omit for none")
	cmd.Flags().StringVar(&flagrule_action, "rule_action", "", "Firewall rule action enum")
	_ = cmd.MarkFlagRequired("rule_action")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	cmd.Flags().StringVar(&flagsource, "source", "", "Source address/network")
	cmd.Flags().StringVar(&flagsport, "sport", "", "Source port")
	cmd.Flags().StringVar(&flagtype, "type", "", "Firewall rule type enum")
	_ = cmd.MarkFlagRequired("type")
	return cmd
}

// registerCreateNotificationCmd returns the cobra command for CreateNotification
// POST /vps/create-notification
func registerCreateNotificationCmd(client *Client) *cobra.Command {
	var flagcpu_usage int
	var flagdata_timeframe int
	var flagdisk_read int
	var flagdisk_write int
	var flagemail_address string
	var flagexceed_all bool
	var flagmemory_usage int
	var flagname string
	var flagnetwork_traffic int
	var flagnotification_interval int
	var flagservice_id string
	var flagstatus string
	cmd := &cobra.Command{
		Use:   "create-notification",
		Short: "Creates a new notification for a VPS service with customizable thresholds for CPU, memory, network, and disk metrics",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"cpu_usage": flagcpu_usage,
				"data_timeframe": flagdata_timeframe,
				"disk_read": flagdisk_read,
				"disk_write": flagdisk_write,
				"email_address": flagemail_address,
				"exceed_all": flagexceed_all,
				"memory_usage": flagmemory_usage,
				"name": flagname,
				"network_traffic": flagnetwork_traffic,
				"notification_interval": flagnotification_interval,
				"service_id": flagservice_id,
				"status": flagstatus,
			}
			return client.Do("POST", "/vps/create-notification", body)
		},
	}
	cmd.Flags().IntVar(&flagcpu_usage, "cpu_usage", 0, "CPU usage threshold percentage (0-100)")
	cmd.Flags().IntVar(&flagdata_timeframe, "data_timeframe", 0, "Data timeframe in minutes (must be > 0)")
	cmd.Flags().IntVar(&flagdisk_read, "disk_read", 0, "Disk read threshold percentage (0-100)")
	cmd.Flags().IntVar(&flagdisk_write, "disk_write", 0, "Disk write threshold percentage (0-100)")
	cmd.Flags().StringVar(&flagemail_address, "email_address", "", "Email addresses for notifications (comma-separated string or array)")
	cmd.Flags().BoolVar(&flagexceed_all, "exceed_all", false, "Whether all thresholds must be exceeded (true) or any one (false)")
	cmd.Flags().IntVar(&flagmemory_usage, "memory_usage", 0, "Memory usage threshold percentage (0-100)")
	cmd.Flags().StringVar(&flagname, "name", "", "Name/title for the notification")
	_ = cmd.MarkFlagRequired("name")
	cmd.Flags().IntVar(&flagnetwork_traffic, "network_traffic", 0, "Network traffic threshold percentage (0-100)")
	cmd.Flags().IntVar(&flagnotification_interval, "notification_interval", 0, "Notification interval in minutes (must be > 0)")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	cmd.Flags().StringVar(&flagstatus, "status", "", "Notification status values")
	return cmd
}

// registerCreateOrderCmd returns the cobra command for CreateOrder
// POST /vps/create-order
func registerCreateOrderCmd(client *Client) *cobra.Command {
	var flagproducts string
	var flagpromo string
	cmd := &cobra.Command{
		Use:   "create-order",
		Short: "Creates an order through checkout. Returns payment status; on failure also includes payment_error with code and message.",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"products": flagproducts,
				"promo": flagpromo,
			}
			return client.Do("POST", "/vps/create-order", body)
		},
	}
	cmd.Flags().StringVar(&flagproducts, "products", "", "List of products to order")
	_ = cmd.MarkFlagRequired("products")
	cmd.Flags().StringVar(&flagpromo, "promo", "", "Promotional code to apply to the order")
	return cmd
}

// registerCreatePowerTaskCmd returns the cobra command for CreatePowerTask
// POST /vps/create-power-task
func registerCreatePowerTaskCmd(client *Client) *cobra.Command {
	var flagdays string
	var flagdescription string
	var flagend_date string
	var flagend_time string
	var flagjob_hour int
	var flagjob_minutes int
	var flagjob_time string
	var flagjob_type string
	var flagpower_task_action string
	var flagservice_id string
	var flagstart_date string
	var flagstart_time string
	cmd := &cobra.Command{
		Use:   "create-power-task",
		Short: "Creates a new power task (scheduled start/stop/restart operation) for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"days": flagdays,
				"description": flagdescription,
				"end_date": flagend_date,
				"end_time": flagend_time,
				"job_hour": flagjob_hour,
				"job_minutes": flagjob_minutes,
				"job_time": flagjob_time,
				"job_type": flagjob_type,
				"power_task_action": flagpower_task_action,
				"service_id": flagservice_id,
				"start_date": flagstart_date,
				"start_time": flagstart_time,
			}
			return client.Do("POST", "/vps/create-power-task", body)
		},
	}
	cmd.Flags().StringVar(&flagdays, "days", "", "Days of the week for weekly jobs (array of mon, tue, wed, thu, fri, sat, sun)")
	cmd.Flags().StringVar(&flagdescription, "description", "", "Description of the power task")
	cmd.Flags().StringVar(&flagend_date, "end_date", "", "End date in Y-m-d format (e.g., 2026-12-31)")
	cmd.Flags().StringVar(&flagend_time, "end_time", "", "End time in HH:MM or HH:MM:SS format")
	cmd.Flags().IntVar(&flagjob_hour, "job_hour", 0, "Job hour (alternative to job_time)")
	cmd.Flags().IntVar(&flagjob_minutes, "job_minutes", 0, "Job minutes (alternative to job_time)")
	cmd.Flags().StringVar(&flagjob_time, "job_time", "", "Job execution time in HH:MM or HH:MM:SS format")
	cmd.Flags().StringVar(&flagjob_type, "job_type", "", "Job type: oneTime, daily, or weekly")
	cmd.Flags().StringVar(&flagpower_task_action, "power_task_action", "", "Power action to perform (start, stop, restart)")
	_ = cmd.MarkFlagRequired("power_task_action")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	cmd.Flags().StringVar(&flagstart_date, "start_date", "", "Start date in Y-m-d format (e.g., 2026-03-25)")
	_ = cmd.MarkFlagRequired("start_date")
	cmd.Flags().StringVar(&flagstart_time, "start_time", "", "Start time in HH:MM or HH:MM:SS format")
	return cmd
}

// registerCreateSnapshotCmd returns the cobra command for CreateSnapshot
// POST /vps/create-snapshot
func registerCreateSnapshotCmd(client *Client) *cobra.Command {
	var flagdescription string
	var flagservice_id string
	var flagsnapname string
	cmd := &cobra.Command{
		Use:   "create-snapshot",
		Short: "Creates a new snapshot for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"description": flagdescription,
				"service_id": flagservice_id,
				"snapname": flagsnapname,
			}
			return client.Do("POST", "/vps/create-snapshot", body)
		},
	}
	cmd.Flags().StringVar(&flagdescription, "description", "", "Description for the snapshot")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	cmd.Flags().StringVar(&flagsnapname, "snapname", "", "Name for the snapshot")
	return cmd
}

// registerDeleteBackupCmd returns the cobra command for DeleteBackup
// POST /vps/delete-backup
func registerDeleteBackupCmd(client *Client) *cobra.Command {
	var flagbackup_id int
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "delete-backup",
		Short: "Deletes a specific backup from a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"backup_id": flagbackup_id,
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/delete-backup", body)
		},
	}
	cmd.Flags().IntVar(&flagbackup_id, "backup_id", 0, "Backup ID to delete")
	_ = cmd.MarkFlagRequired("backup_id")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerDeleteBackupScheduleCmd returns the cobra command for DeleteBackupSchedule
// POST /vps/delete-backup-schedule
func registerDeleteBackupScheduleCmd(client *Client) *cobra.Command {
	var flagschedule_id string
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "delete-backup-schedule",
		Short: "Deletes a backup schedule from a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"schedule_id": flagschedule_id,
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/delete-backup-schedule", body)
		},
	}
	cmd.Flags().StringVar(&flagschedule_id, "schedule_id", "", "Backup schedule ID to delete")
	_ = cmd.MarkFlagRequired("schedule_id")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerDeleteFirewallRuleCmd returns the cobra command for DeleteFirewallRule
// POST /vps/delete-firewall-rule
func registerDeleteFirewallRuleCmd(client *Client) *cobra.Command {
	var flagpos int
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "delete-firewall-rule",
		Short: "Deletes a firewall rule from a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"pos": flagpos,
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/delete-firewall-rule", body)
		},
	}
	cmd.Flags().IntVar(&flagpos, "pos", 0, "Position/index of the rule to delete")
	_ = cmd.MarkFlagRequired("pos")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerDeleteNotificationCmd returns the cobra command for DeleteNotification
// POST /vps/delete-notification
func registerDeleteNotificationCmd(client *Client) *cobra.Command {
	var flagnotification_id int
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "delete-notification",
		Short: "Deletes a notification from a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"notification_id": flagnotification_id,
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/delete-notification", body)
		},
	}
	cmd.Flags().IntVar(&flagnotification_id, "notification_id", 0, "Notification ID to delete")
	_ = cmd.MarkFlagRequired("notification_id")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerDeletePowerTaskCmd returns the cobra command for DeletePowerTask
// POST /vps/delete-power-task
func registerDeletePowerTaskCmd(client *Client) *cobra.Command {
	var flagservice_id string
	var flagtask_id int
	cmd := &cobra.Command{
		Use:   "delete-power-task",
		Short: "Deletes a power task from a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
				"task_id": flagtask_id,
			}
			return client.Do("POST", "/vps/delete-power-task", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	cmd.Flags().IntVar(&flagtask_id, "task_id", 0, "Power task ID to delete")
	_ = cmd.MarkFlagRequired("task_id")
	return cmd
}

// registerDeleteSnapshotCmd returns the cobra command for DeleteSnapshot
// POST /vps/delete-snapshot
func registerDeleteSnapshotCmd(client *Client) *cobra.Command {
	var flagservice_id string
	var flagsnapshot_name string
	cmd := &cobra.Command{
		Use:   "delete-snapshot",
		Short: "Deletes a specific snapshot from a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
				"snapshot_name": flagsnapshot_name,
			}
			return client.Do("POST", "/vps/delete-snapshot", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	cmd.Flags().StringVar(&flagsnapshot_name, "snapshot_name", "", "Snapshot name to delete")
	_ = cmd.MarkFlagRequired("snapshot_name")
	return cmd
}

// registerEditBackupScheduleCmd returns the cobra command for EditBackupSchedule
// POST /vps/edit-backup-schedule
func registerEditBackupScheduleCmd(client *Client) *cobra.Command {
	var flagcompress string
	var flagdow string
	var flagmailto bool
	var flagmode string
	var flagschedule_id string
	var flagservice_id string
	var flagstarttime string
	cmd := &cobra.Command{
		Use:   "edit-backup-schedule",
		Short: "Edits an existing backup schedule for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"compress": flagcompress,
				"dow": flagdow,
				"mailto": flagmailto,
				"mode": flagmode,
				"schedule_id": flagschedule_id,
				"service_id": flagservice_id,
				"starttime": flagstarttime,
			}
			return client.Do("POST", "/vps/edit-backup-schedule", body)
		},
	}
	cmd.Flags().StringVar(&flagcompress, "compress", "", "Backup compression type enum")
	_ = cmd.MarkFlagRequired("compress")
	cmd.Flags().StringVar(&flagdow, "dow", "", "Days of week when backup should run. Valid values: mon, tue, wed, thu, fri, sat, sun. Provide as an array of day names.")
	_ = cmd.MarkFlagRequired("dow")
	cmd.Flags().BoolVar(&flagmailto, "mailto", false, "Email notification setting. Set to true to send notifications to client's email, false or omit to disable")
	cmd.Flags().StringVar(&flagmode, "mode", "", "Backup mode. Valid values: 'snapshot', 'suspend', 'stop'")
	_ = cmd.MarkFlagRequired("mode")
	cmd.Flags().StringVar(&flagschedule_id, "schedule_id", "", "Backup schedule ID to edit")
	_ = cmd.MarkFlagRequired("schedule_id")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	cmd.Flags().StringVar(&flagstarttime, "starttime", "", "Time in HH:MM format (e.g., '03:00'). Hours must be between 00-23, minutes must be between 00-59")
	_ = cmd.MarkFlagRequired("starttime")
	return cmd
}

// registerGetCatalogueCmd returns the cobra command for GetCatalogue
// POST /vps/get-catalogue
func registerGetCatalogueCmd(client *Client) *cobra.Command {
	var flaggroup_id string
	var flagproduct_id string
	cmd := &cobra.Command{
		Use:   "get-catalogue",
		Short: "Retrieves the product catalogue, optionally filtered by group or product",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"group_id": flaggroup_id,
				"product_id": flagproduct_id,
			}
			return client.Do("POST", "/vps/get-catalogue", body)
		},
	}
	cmd.Flags().StringVar(&flaggroup_id, "group_id", "", "Optional group identifier to filter catalogue results")
	cmd.Flags().StringVar(&flagproduct_id, "product_id", "", "Optional product identifier to filter catalogue results")
	return cmd
}

// registerGetVpsConfigCmd returns the cobra command for GetVpsConfig
// POST /vps/get-config
func registerGetVpsConfigCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "get-vps-config",
		Short: "Retrieves VPS configuration settings including name, hostname, auto-start, boot order, and CD-ROM",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/get-config", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerGetVpsDetailsCmd returns the cobra command for GetVpsDetails
// POST /vps/get-details
func registerGetVpsDetailsCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "get-vps-details",
		Short: "Gets detailed information about a VPS service including configuration, network settings, and statistics",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/get-details", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerGetOsTemplateDetailsCmd returns the cobra command for GetOsTemplateDetails
// POST /vps/get-os-template-details
func registerGetOsTemplateDetailsCmd(client *Client) *cobra.Command {
	var flagimageId string
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "get-os-template-details",
		Short: "[Under development] Retrieves detailed information about a specific OS template",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"imageId": flagimageId,
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/get-os-template-details", body)
		},
	}
	cmd.Flags().StringVar(&flagimageId, "imageId", "", "Image identifier for the OS template")
	_ = cmd.MarkFlagRequired("imageId")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerGetPrivateSshKeyCmd returns the cobra command for GetPrivateSshKey
// POST /vps/get-private-ssh-keys
func registerGetPrivateSshKeyCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "get-private-ssh-key",
		Short: "Retrieves the private SSH key configured for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/get-private-ssh-keys", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerGetPublicSshKeyCmd returns the cobra command for GetPublicSshKey
// POST /vps/get-public-ssh-keys
func registerGetPublicSshKeyCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "get-public-ssh-key",
		Short: "Retrieves the public SSH key configured for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/get-public-ssh-keys", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerListAllowedFeaturesCmd returns the cobra command for ListAllowedFeatures
// POST /vps/list-allowed-features
func registerListAllowedFeaturesCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "list-allowed-features",
		Short: "Gets the allowed features and capabilities for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/list-allowed-features", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerListBackupSchedulesCmd returns the cobra command for ListBackupSchedules
// POST /vps/list-backup-schedules
func registerListBackupSchedulesCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "list-backup-schedules",
		Short: "Retrieves the list of backup schedules for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/list-backup-schedules", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerListBackupsCmd returns the cobra command for ListBackups
// POST /vps/list-backups
func registerListBackupsCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "list-backups",
		Short: "Retrieves the list of backups for a VPS service including quota information and backup configuration options",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/list-backups", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerListFirewallRulesCmd returns the cobra command for ListFirewallRules
// POST /vps/list-firewall-rules
func registerListFirewallRulesCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "list-firewall-rules",
		Short: "Retrieves the list of firewall rules and available options for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/list-firewall-rules", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerListIsosCmd returns the cobra command for ListIsos
// POST /vps/list-isos
func registerListIsosCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "list-isos",
		Short: "Retrieves the list of available ISO images for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/list-isos", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerListNotificationsCmd returns the cobra command for ListNotifications
// POST /vps/list-notifications
func registerListNotificationsCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "list-notifications",
		Short: "Retrieves the list of notifications for a VPS service along with dialog rules for creating notifications",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/list-notifications", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerListOrdersCmd returns the cobra command for ListOrders
// POST /vps/list-orders
func registerListOrdersCmd(client *Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list-orders",
		Short: "Lists all orders for the authenticated user, including payment and invoice status",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
			}
			return client.Do("POST", "/vps/list-orders", body)
		},
	}
	return cmd
}

// registerListOsTemplatesCmd returns the cobra command for ListOsTemplates
// POST /vps/list-os-templates
func registerListOsTemplatesCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "list-os-templates",
		Short: "[Under development] Retrieves the list of available OS templates",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/list-os-templates", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerListPowerTasksCmd returns the cobra command for ListPowerTasks
// POST /vps/list-power-tasks
func registerListPowerTasksCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "list-power-tasks",
		Short: "Retrieves the list of power tasks (scheduled start/stop/restart operations) for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/list-power-tasks", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerListReinstallOsCmd returns the cobra command for ListReinstallOs
// POST /vps/list-reinstall-images
func registerListReinstallOsCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "list-reinstall-os",
		Short: "[Under development] Retrieves the list of available OS images for VPS reinstallation",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/list-reinstall-images", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerListSnapshotsCmd returns the cobra command for ListSnapshots
// POST /vps/list-snapshots
func registerListSnapshotsCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "list-snapshots",
		Short: "Retrieves the list of snapshots for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/list-snapshots", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerListVpsServicesCmd returns the cobra command for ListVpsServices
// POST /vps/list-vps-services
func registerListVpsServicesCmd(client *Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list-vps-services",
		Short: "Lists all VPS services accessible by the authenticated user",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
			}
			return client.Do("POST", "/vps/list-vps-services", body)
		},
	}
	return cmd
}

// registerMountIsoCmd returns the cobra command for MountIso
// POST /vps/mount-iso
func registerMountIsoCmd(client *Client) *cobra.Command {
	var flagformat_master_disk bool
	var flagiso string
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "mount-iso",
		Short: "Mounts an ISO image on a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"format_master_disk": flagformat_master_disk,
				"iso": flagiso,
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/mount-iso", body)
		},
	}
	cmd.Flags().BoolVar(&flagformat_master_disk, "format_master_disk", false, "Whether to format the master disk before mounting the ISO")
	cmd.Flags().StringVar(&flagiso, "iso", "", "Name of the ISO image to mount")
	_ = cmd.MarkFlagRequired("iso")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerMoveFirewallRuleCmd returns the cobra command for MoveFirewallRule
// POST /vps/move-firewall-rule
func registerMoveFirewallRuleCmd(client *Client) *cobra.Command {
	var flagdirection string
	var flagpos int
	var flagservice_id string
	var flagtarget_pos int
	cmd := &cobra.Command{
		Use:   "move-firewall-rule",
		Short: "Moves a firewall rule to a different position in the rule list. Supports both absolute positioning (target_pos) and relative movement (direction). Exactly one of target_pos or direction must be provided.",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"direction": flagdirection,
				"pos": flagpos,
				"service_id": flagservice_id,
				"target_pos": flagtarget_pos,
			}
			return client.Do("POST", "/vps/move-firewall-rule", body)
		},
	}
	cmd.Flags().StringVar(&flagdirection, "direction", "", "Firewall rule move direction enum")
	cmd.Flags().IntVar(&flagpos, "pos", 0, "Current position/index of the rule to move")
	_ = cmd.MarkFlagRequired("pos")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	cmd.Flags().IntVar(&flagtarget_pos, "target_pos", 0, "Target position/index for the rule (mutually exclusive with direction)")
	return cmd
}

// registerGetNoVncConsoleCmd returns the cobra command for GetNoVncConsole
// POST /vps/novnc-console
func registerGetNoVncConsoleCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "get-no-vnc-console",
		Short: "Retrieves noVNC console access credentials and connection details for a VPS",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/novnc-console", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerRebootVpsCmd returns the cobra command for RebootVps
// POST /vps/reboot
func registerRebootVpsCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "reboot-vps",
		Short: "Gracefully reboot a VPS service. Sends ACPI reboot signal to guest OS",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/reboot", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerRestoreBackupCmd returns the cobra command for RestoreBackup
// POST /vps/restore-backup
func registerRestoreBackupCmd(client *Client) *cobra.Command {
	var flagbackup_id string
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "restore-backup",
		Short: "Restores a VPS from a backup with the specified backup identifier",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"backup_id": flagbackup_id,
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/restore-backup", body)
		},
	}
	cmd.Flags().StringVar(&flagbackup_id, "backup_id", "", "Backup identifier for the backup to restore")
	_ = cmd.MarkFlagRequired("backup_id")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerRetryPaymentCmd returns the cobra command for RetryPayment
// POST /vps/retry-payment
func registerRetryPaymentCmd(client *Client) *cobra.Command {
	var flagorder_id int
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "retry-payment",
		Short: "Retries a failed or pending payment for an existing order",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"order_id": flagorder_id,
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/retry-payment", body)
		},
	}
	cmd.Flags().IntVar(&flagorder_id, "order_id", 0, "The order identifier to retry payment for")
	_ = cmd.MarkFlagRequired("order_id")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerRollbackSnapshotCmd returns the cobra command for RollbackSnapshot
// POST /vps/rollback-snapshot
func registerRollbackSnapshotCmd(client *Client) *cobra.Command {
	var flagservice_id string
	var flagsnapshot_name string
	cmd := &cobra.Command{
		Use:   "rollback-snapshot",
		Short: "[Under development] Rolls back a VPS to a previous snapshot state",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
				"snapshot_name": flagsnapshot_name,
			}
			return client.Do("POST", "/vps/rollback-snapshot", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	cmd.Flags().StringVar(&flagsnapshot_name, "snapshot_name", "", "Snapshot name to rollback to")
	_ = cmd.MarkFlagRequired("snapshot_name")
	return cmd
}

// registerShutdownVpsCmd returns the cobra command for ShutdownVps
// POST /vps/shutdown
func registerShutdownVpsCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "shutdown-vps",
		Short: "Gracefully shutdown a VPS service. Sends ACPI shutdown signal to guest OS",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/shutdown", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerStartVpsCmd returns the cobra command for StartVps
// POST /vps/start
func registerStartVpsCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "start-vps",
		Short: "Starts a stopped VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/start", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerStopVpsCmd returns the cobra command for StopVps
// POST /vps/stop
func registerStopVpsCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "stop-vps",
		Short: "Hard stops a running VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/stop", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerSuspendVpsCmd returns the cobra command for SuspendVps
// POST /vps/suspend
func registerSuspendVpsCmd(client *Client) *cobra.Command {
	var flagservice_id string
	var flagsuspend_reason string
	cmd := &cobra.Command{
		Use:   "suspend-vps",
		Short: "[Under development] Suspends an active VPS service through WHMCS. Requires a reason for suspension",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
				"suspend_reason": flagsuspend_reason,
			}
			return client.Do("POST", "/vps/suspend", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	cmd.Flags().StringVar(&flagsuspend_reason, "suspend_reason", "", "Reason for suspending the service")
	_ = cmd.MarkFlagRequired("suspend_reason")
	return cmd
}

// registerTerminateVpsCmd returns the cobra command for TerminateVps
// POST /vps/terminate
func registerTerminateVpsCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "terminate-vps",
		Short: "[Under development] Terminates a VPS service through WHMCS. This action is irreversible",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/terminate", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerTriggerReinstallCmd returns the cobra command for TriggerReinstall
// POST /vps/trigger-reinstall
func registerTriggerReinstallCmd(client *Client) *cobra.Command {
	var flagservice_id string
	var flagtemplate string
	cmd := &cobra.Command{
		Use:   "trigger-reinstall",
		Short: "Triggers a VPS reinstallation with the specified OS template",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
				"template": flagtemplate,
			}
			return client.Do("POST", "/vps/trigger-reinstall", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	cmd.Flags().StringVar(&flagtemplate, "template", "", "Template identifier for the OS to reinstall")
	_ = cmd.MarkFlagRequired("template")
	return cmd
}

// registerUnsuspendVpsCmd returns the cobra command for UnsuspendVps
// POST /vps/unsuspend
func registerUnsuspendVpsCmd(client *Client) *cobra.Command {
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "unsuspend-vps",
		Short: "[Under development] Unsuspends a suspended VPS service through WHMCS. Can only unsuspend services that were suspended via API",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/unsuspend", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerUpdateVpsConfigCmd returns the cobra command for UpdateVpsConfig
// POST /vps/update-config
func registerUpdateVpsConfigCmd(client *Client) *cobra.Command {
	var flagauto_start int
	var flagboot string
	var flagcdrom string
	var flaghostname string
	var flagide2 string
	var flagname string
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "update-vps-config",
		Short: "Updates VPS configuration settings such as name, hostname, auto-start, boot order, and CD-ROM",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"auto_start": flagauto_start,
				"boot": flagboot,
				"cdrom": flagcdrom,
				"hostname": flaghostname,
				"ide2": flagide2,
				"name": flagname,
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/update-config", body)
		},
	}
	cmd.Flags().IntVar(&flagauto_start, "auto_start", 0, "Auto-start on boot (0 or 1)")
	cmd.Flags().StringVar(&flagboot, "boot", "", "Boot order configuration")
	cmd.Flags().StringVar(&flagcdrom, "cdrom", "", "CD-ROM configuration")
	cmd.Flags().StringVar(&flaghostname, "hostname", "", "New hostname for the VPS")
	cmd.Flags().StringVar(&flagide2, "ide2", "", "IDE2 device configuration")
	cmd.Flags().StringVar(&flagname, "name", "", "New name for the VPS")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerUpdateFirewallRuleCmd returns the cobra command for UpdateFirewallRule
// POST /vps/update-firewall-rule
func registerUpdateFirewallRuleCmd(client *Client) *cobra.Command {
	var flagcomment string
	var flagpos int
	var flagrule_action string
	var flagservice_id string
	cmd := &cobra.Command{
		Use:   "update-firewall-rule",
		Short: "Updates an existing firewall rule for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"comment": flagcomment,
				"pos": flagpos,
				"rule_action": flagrule_action,
				"service_id": flagservice_id,
			}
			return client.Do("POST", "/vps/update-firewall-rule", body)
		},
	}
	cmd.Flags().StringVar(&flagcomment, "comment", "", "Comment/description for the rule")
	cmd.Flags().IntVar(&flagpos, "pos", 0, "Position/index of the rule to update")
	_ = cmd.MarkFlagRequired("pos")
	cmd.Flags().StringVar(&flagrule_action, "rule_action", "", "Firewall rule action enum")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	return cmd
}

// registerUpdateNotificationCmd returns the cobra command for UpdateNotification
// POST /vps/update-notification
func registerUpdateNotificationCmd(client *Client) *cobra.Command {
	var flagcpu_usage int
	var flagdata_timeframe int
	var flagdisk_read int
	var flagdisk_write int
	var flagemail_address string
	var flagexceed_all bool
	var flagmemory_usage int
	var flagname string
	var flagnetwork_traffic int
	var flagnotification_id int
	var flagnotification_interval int
	var flagservice_id string
	var flagstatus string
	cmd := &cobra.Command{
		Use:   "update-notification",
		Short: "Updates an existing notification for a VPS service with customizable thresholds for CPU, memory, network, and disk metrics",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"cpu_usage": flagcpu_usage,
				"data_timeframe": flagdata_timeframe,
				"disk_read": flagdisk_read,
				"disk_write": flagdisk_write,
				"email_address": flagemail_address,
				"exceed_all": flagexceed_all,
				"memory_usage": flagmemory_usage,
				"name": flagname,
				"network_traffic": flagnetwork_traffic,
				"notification_id": flagnotification_id,
				"notification_interval": flagnotification_interval,
				"service_id": flagservice_id,
				"status": flagstatus,
			}
			return client.Do("POST", "/vps/update-notification", body)
		},
	}
	cmd.Flags().IntVar(&flagcpu_usage, "cpu_usage", 0, "CPU usage threshold percentage (0-100)")
	cmd.Flags().IntVar(&flagdata_timeframe, "data_timeframe", 0, "Data timeframe in minutes (must be > 0)")
	cmd.Flags().IntVar(&flagdisk_read, "disk_read", 0, "Disk read threshold percentage (0-100)")
	cmd.Flags().IntVar(&flagdisk_write, "disk_write", 0, "Disk write threshold percentage (0-100)")
	cmd.Flags().StringVar(&flagemail_address, "email_address", "", "Email addresses for notifications (comma-separated string or array)")
	cmd.Flags().BoolVar(&flagexceed_all, "exceed_all", false, "Whether all thresholds must be exceeded (true) or any one (false)")
	cmd.Flags().IntVar(&flagmemory_usage, "memory_usage", 0, "Memory usage threshold percentage (0-100)")
	cmd.Flags().StringVar(&flagname, "name", "", "Name/title for the notification")
	cmd.Flags().IntVar(&flagnetwork_traffic, "network_traffic", 0, "Network traffic threshold percentage (0-100)")
	cmd.Flags().IntVar(&flagnotification_id, "notification_id", 0, "Notification ID to update")
	_ = cmd.MarkFlagRequired("notification_id")
	cmd.Flags().IntVar(&flagnotification_interval, "notification_interval", 0, "Notification interval in minutes (must be > 0)")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	cmd.Flags().StringVar(&flagstatus, "status", "", "Notification status values")
	return cmd
}

// registerUpdatePowerTaskCmd returns the cobra command for UpdatePowerTask
// POST /vps/update-power-task
func registerUpdatePowerTaskCmd(client *Client) *cobra.Command {
	var flagdays string
	var flagdescription string
	var flagend_date string
	var flagend_time string
	var flagjob_hour int
	var flagjob_minutes int
	var flagjob_time string
	var flagjob_type string
	var flagpower_task_action string
	var flagservice_id string
	var flagstart_date string
	var flagstart_time string
	var flagtask_id int
	cmd := &cobra.Command{
		Use:   "update-power-task",
		Short: "Updates an existing power task (scheduled start/stop/restart operation) for a VPS service",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"days": flagdays,
				"description": flagdescription,
				"end_date": flagend_date,
				"end_time": flagend_time,
				"job_hour": flagjob_hour,
				"job_minutes": flagjob_minutes,
				"job_time": flagjob_time,
				"job_type": flagjob_type,
				"power_task_action": flagpower_task_action,
				"service_id": flagservice_id,
				"start_date": flagstart_date,
				"start_time": flagstart_time,
				"task_id": flagtask_id,
			}
			return client.Do("POST", "/vps/update-power-task", body)
		},
	}
	cmd.Flags().StringVar(&flagdays, "days", "", "Days of the week for weekly jobs (array of mon, tue, wed, thu, fri, sat, sun)")
	cmd.Flags().StringVar(&flagdescription, "description", "", "Description of the power task")
	cmd.Flags().StringVar(&flagend_date, "end_date", "", "End date in Y-m-d format (e.g., 2026-12-31)")
	cmd.Flags().StringVar(&flagend_time, "end_time", "", "End time in HH:MM or HH:MM:SS format")
	cmd.Flags().IntVar(&flagjob_hour, "job_hour", 0, "Job hour (alternative to job_time)")
	cmd.Flags().IntVar(&flagjob_minutes, "job_minutes", 0, "Job minutes (alternative to job_time)")
	cmd.Flags().StringVar(&flagjob_time, "job_time", "", "Job execution time in HH:MM or HH:MM:SS format")
	cmd.Flags().StringVar(&flagjob_type, "job_type", "", "Job type: oneTime, daily, or weekly")
	cmd.Flags().StringVar(&flagpower_task_action, "power_task_action", "", "Power action to perform (start, stop, restart)")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	cmd.Flags().StringVar(&flagstart_date, "start_date", "", "Start date in Y-m-d format (e.g., 2026-03-25)")
	cmd.Flags().StringVar(&flagstart_time, "start_time", "", "Start time in HH:MM or HH:MM:SS format")
	cmd.Flags().IntVar(&flagtask_id, "task_id", 0, "Power task ID to update")
	_ = cmd.MarkFlagRequired("task_id")
	return cmd
}

// registerUpdateSnapshotCmd returns the cobra command for UpdateSnapshot
// POST /vps/update-snapshot
func registerUpdateSnapshotCmd(client *Client) *cobra.Command {
	var flagdescription string
	var flagservice_id string
	var flagsnapshot_name string
	cmd := &cobra.Command{
		Use:   "update-snapshot",
		Short: "Updates a snapshot's metadata",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"description": flagdescription,
				"service_id": flagservice_id,
				"snapshot_name": flagsnapshot_name,
			}
			return client.Do("POST", "/vps/update-snapshot", body)
		},
	}
	cmd.Flags().StringVar(&flagdescription, "description", "", "New description for the snapshot")
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	cmd.Flags().StringVar(&flagsnapshot_name, "snapshot_name", "", "Snapshot name to update")
	_ = cmd.MarkFlagRequired("snapshot_name")
	return cmd
}

// registerUpdateSshKeysCmd returns the cobra command for UpdateSshKeys
// POST /vps/update-ssh-keys
func registerUpdateSshKeysCmd(client *Client) *cobra.Command {
	var flagservice_id string
	var flagsshKeys string
	cmd := &cobra.Command{
		Use:   "update-ssh-keys",
		Short: "Updates SSH public keys for a VPS service for root access.",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"service_id": flagservice_id,
				"sshKeys": flagsshKeys,
			}
			return client.Do("POST", "/vps/update-ssh-keys", body)
		},
	}
	cmd.Flags().StringVar(&flagservice_id, "service_id", "", "Service ID - must be sent as a string")
	_ = cmd.MarkFlagRequired("service_id")
	cmd.Flags().StringVar(&flagsshKeys, "sshKeys", "", "SSH public key in OpenSSH format (must start with ssh-rsa, ssh-dss, ssh-ed25519, or ssh-ecdsa)")
	_ = cmd.MarkFlagRequired("sshKeys")
	return cmd
}

// registerValidatePricingCmd returns the cobra command for ValidatePricing
// POST /vps/validate-pricing
func registerValidatePricingCmd(client *Client) *cobra.Command {
	var flagproducts string
	var flagpromo string
	cmd := &cobra.Command{
		Use:   "validate-pricing",
		Short: "Validates pricing for one or more products, returning per-product breakdown and order summary",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]interface{}{
				"products": flagproducts,
				"promo": flagpromo,
			}
			return client.Do("POST", "/vps/validate-pricing", body)
		},
	}
	cmd.Flags().StringVar(&flagproducts, "products", "", "List of products to validate pricing for")
	_ = cmd.MarkFlagRequired("products")
	cmd.Flags().StringVar(&flagpromo, "promo", "", "Optional promotional code to apply")
	return cmd
}
